### ISSUE TITLE
Conflict with recent iOS9 update?

### ISSUE THREAD

**Issue by seanbonner** [Safecast/Drive-ios#4]
Several users experiencing the same issue, which just started happening. See discussion here:

https://groups.google.com/forum/#!topic/safecast-devices/IaAastfnL8A

Basically when opening the app it loads for a second and then seems to quit, though it's still active in the background. Using app picker to bring it back to the front works for only a second and it goes right back into background, making it impossible to do anything in the app.

**Comment by mcrollin** [comment]
Seems like this issue is solved.
